---
title: "Phylogenetic, geographic, and ecological predictors of parasitism in North American squirrel species"
author: Randi H. Griffin, Sania Rahim, Mirjam Ansorge, Natalie Cooper, Charles L. Nunn, and others???
output: html_document
---

<br>
[<-- Back to Projects](../projects.html)
<br>
<a target="_blank" href="https://github.com/rgriff23">Go to Github --></a>

___

This project combines data from a wide array of sources to investigate whether phylogenetic, geographic, and ecological factors predict patterns of parasitism in North American squirrel species, similar to this study conducted in primates by Cooper et al., (2012). The types of data we are working with include comparative data on parasites and host traits for a range of squirrel species, publicly available data from geographic information systems, and phylogenetic data from studies on mammalian systematics. 

The key resource for this project is a relational database of published host-parasite reports for North American squirrels, which was originally compiled by Natalie Cooper and Marjam Ansorge at Trinity College Dublin. More recently, under my mentorship, Sania Rahim has added to this database and helped perform some preliminary analyses on the data for her senior undergraduate thesis at Duke University. Currently, Debapriyo Chakraborty, a post-doctoral researcher in my lab and member of Sania Rahim's thesis committee, has expressed interest in cleaning up the database and adding high-resolution georeferencing to the host-parasite reports. If/when the database is ready, I'll be contributing to the analysis part of the project. 

## References

Cooper, N., <b>Griffin, R.</b>, Franz, M., Omotayo, M., and Nunn, C.L. 2012. Phylogenetic host specificity and understanding parasite sharing in primates. Ecology Letters 15(12):1370-77.

___

[<-- Back to Projects](http://rgriff23.github.io/projects.html)